management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - prometheus
          - metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
