global:
  scrape_interval: 5s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets:
          - '9667-45-181-196-198.sa.ngrok.io'